package core.constants;

public enum FindByLocator {
    TEXT,
    NAME,
    ID,
    XPATH,
    LABEL,
    CLASS,
    ACCESSIBILITY_LABEL,
    ACCESSIBILITY_IDENTIFIER,
    PARTIAL_TEXT,
    CONTENT_DESCRIPTION,
    RESOURCE_ID_AND_TEXT,
    RESOURCE_ID_AND_PARTIAL_TEXT,
    ACCESSIBILITY_LABEL_AND_TEXT,
    ACCESSIBILITY_IDENTIFIER_AND_TEXT,
}
